import * as path from "node:path";
import * as fs from "node:fs";
import * as process from "node:process";

import {
  Communicator,
  GenerationRecipe,
  Helper,
  ImageFeature,
  ImageFeatureFormat,
  ImageFeatureType,
  ImageMetadata,
  NotificationEvent,
  NotificationsDialogType,
  NotificationValue,
  PicteusExtension,
  PromptKind,
  SettingsValue
} from "@picteus/extension-sdk";


enum ComfyUIConstants
{
  workflow = "workflow",
  prompt = "prompt"
}

type Json = Record<string, any>;

/**
 * The prompt and workflow of an image generated by ComfyUI.
 */
class ComfyUiPromptAndWorkflow
{

  constructor(prompt: Json, workflow: Json)
  {
    this.prompt = prompt;
    this.workflow = workflow;
  }

  readonly prompt: Json;

  readonly workflow: Json;

}

class ComfyUiExtension extends PicteusExtension
{

  private url: string;

  private outputDirectoryPath: string;

  private inputDirectoryPath: string;

  private temporaryDirectoryPath: string;

  private extensionCurrentlyInstalled = false;

  protected async onReady(communicator?: Communicator): Promise<void>
  {
    await this.setup(communicator!, await this.getSettings());
  }

  protected async onSettings(communicator: Communicator, value: SettingsValue): Promise<void>
  {
    await this.setup(communicator, value);
  }

  protected async onEvent(communicator: Communicator, event: string, value: NotificationValue): Promise<any>
  {
    if (event === NotificationEvent.ImageCreated || event === NotificationEvent.ImageUpdated || event === NotificationEvent.ImageComputeTags || event === NotificationEvent.ImageComputeFeatures)
    {
      const imageId: string = value["id"];
      const metadata = await this.getImageApi().imageGetMetadata({ id: imageId });
      if (event === NotificationEvent.ImageCreated || event === NotificationEvent.ImageUpdated || event === NotificationEvent.ImageComputeTags)
      {
        await this.computeTags(imageId, metadata);
      }
      if (event === NotificationEvent.ImageCreated || event === NotificationEvent.ImageUpdated || event === NotificationEvent.ImageComputeFeatures)
      {
        await this.computeFeatures(imageId, metadata);
      }
    }
    else if (event === NotificationEvent.ImageRunCommand)
    {
      const commandId: string = value["commandId"];
      const imageIds: string[] = value["imageIds"];
      const imageId = imageIds[0];
      if (commandId === "editComfyUiWorkflow")
      {
        if (this.extensionCurrentlyInstalled === true && this.url !== undefined)
        {
          await this.openInComfyUi(communicator, imageId);
        }
      }
      else if (commandId === "analyzeComfyUiWorkflow")
      {
        await this.computeDescription(communicator, imageId);
      }
    }
  }

  private async setup(communicator: Communicator, value: SettingsValue): Promise<void>
  {
    this.url = value["value"];
    const directoryPath = value["directoryPath"];
    if (directoryPath !== undefined)
    {
      // We guess the default ComfyUI directory paths
      this.outputDirectoryPath = path.join(directoryPath, "output");
      this.inputDirectoryPath = path.join(directoryPath, "input");
      this.temporaryDirectoryPath = path.join(directoryPath, "temp");
      const comfyUiExtensionDirectoryName = "ComfyUI-Picteus";
      const customNodesDirectoryPath = path.join(directoryPath, "custom_nodes", comfyUiExtensionDirectoryName);
      if (fs.existsSync(customNodesDirectoryPath) === false)
      {
        communicator.sendLog("Installing the ComfyUI extension", "info");
        fs.symlinkSync(path.join(process.cwd(), comfyUiExtensionDirectoryName), customNodesDirectoryPath, "dir");
        await communicator.launchIntent<boolean>({
          dialog: {
            type: NotificationsDialogType.Info,
            title: "ComfyUI extension Installed",
            description: "The extension is installed, you should now restart ComfyUi, so that it is taken into account.",
            buttons: { yes: "OK" }
          }
        });
      }
      if (this.url !== undefined)
      {
        const extensionWebServiceUrl = `${this.url}/picteus/get_directory_paths`;
        let response: Response;
        try
        {
          response = await fetch(extensionWebServiceUrl, { method: "GET" });
        }
        catch (error)
        {
          // It is very likely that the ComfyUI server is not running
          communicator.sendLog(`Failed to communicate with the ComfyUI server'. Reason: '${error.message}'`, "error");
          return;
        }
        const result = await response.text();
        if (response.ok === true)
        {
          const jsonObject = JSON.parse(result);
          this.outputDirectoryPath = jsonObject["outputDirectoryPath"];
          this.inputDirectoryPath = jsonObject["inputDirectoryPath"];
          this.temporaryDirectoryPath = jsonObject["temporaryDirectoryPath"];
        }
        else
        {
          communicator.sendLog(`Failed to retrieve the ComfyUI output directory path via the extension web service at '${extensionWebServiceUrl}'. Reason: '${result}'`, "error");
        }
      }
      this.extensionCurrentlyInstalled = true;
    }
  }

  private async computeTags(imageId: string, metadata: ImageMetadata): Promise<void>
  {
    const promptAndWorkflow: ComfyUiPromptAndWorkflow | undefined = this.computePromptAndWorkflow(metadata);
    await this.getImageApi().imageSetTags({
      id: imageId,
      extensionId: this.extensionId,
      requestBody: promptAndWorkflow !== undefined ? [this.extensionId] : []
    });
  }

  private async computeFeatures(imageId: string, metadata: ImageMetadata): Promise<void>
  {
    const promptAndWorkflow: ComfyUiPromptAndWorkflow | undefined = this.computePromptAndWorkflow(metadata);
    if (promptAndWorkflow !== undefined)
    {
      const recipe: GenerationRecipe =
        {
          schemaVersion: Helper.GENERATION_RECIPE_SCHEMA_VERSION,
          modelTags: [],
          software: "comfyui",
          prompt: { kind: PromptKind.Instructions, value: promptAndWorkflow }
        };
      await this.getImageApi().imageSetFeatures({
        id: imageId,
        extensionId: this.extensionId,
        imageFeature: [
          {
            type: ImageFeatureType.Recipe,
            format: ImageFeatureFormat.Json,
            value: JSON.stringify(recipe)
          }
        ]
      });
    }
  }

  private async computeDescription(communicator: Communicator, imageId: string): Promise<void>
  {
    const directoryPaths = [this.outputDirectoryPath, this.inputDirectoryPath, this.temporaryDirectoryPath].filter(directoryPath => directoryPath !== undefined);
    const imageFeatures: Array<ImageFeature> = [];
    if (directoryPaths.length > 0)
    {
      const filePaths: string[] = [];
      const metadata = await this.getImageApi().imageGetMetadata({ id: imageId });
      const promptAndWorkflow: ComfyUiPromptAndWorkflow = this.computePromptAndWorkflow(metadata);
      const workflow = promptAndWorkflow.workflow;
      for (const node of workflow.nodes)
      {
        if (node["type"] === "LoadImage")
        {
          const fileName: string = node["widgets_values"][0];
          for (const directoryPath of directoryPaths)
          {
            const filePath = path.join(directoryPath, fileName);
            if (fs.existsSync(filePath) === true)
            {
              filePaths.push(filePath);
              break;
            }
          }
        }
      }
      const value: string = filePaths.length === 0 ? "No image has been detected as an input image" : `The image was built on the following images: [${filePaths.map(filePath =>
        `'${filePath}'`).join(", ")}]`;
      imageFeatures.push({
        type: ImageFeatureType.Description,
        format: ImageFeatureFormat.String,
        value: value
      });
      await communicator.launchIntent<void>({
        dialog: {
          type: NotificationsDialogType.Info,
          title: "ComfyUI Analysis",
          description: `After having inspected the image metadata, here is the output of the analysis regarding the images that were detected as input images.`,
          details: `${value}.`,
          buttons: { yes: "OK" }
        }
      });
    }
    if (Math.random() > 1)
    {
      await this.getImageApi().imageSetFeatures({
        id: imageId,
        extensionId: this.parameters.extensionId,
        imageFeature: imageFeatures
      });
    }
  }

  private async openInComfyUi(communicator: Communicator, imageId: string): Promise<void>
  {
    const metadata = await this.getImageApi().imageGetMetadata({ id: imageId });
    const promptAndWorkflow: ComfyUiPromptAndWorkflow = this.computePromptAndWorkflow(metadata);
    const workflow = promptAndWorkflow.workflow;
    const extensionWebServiceUrl = `${this.url}/picteus/load_workflow`;
    try
    {
      await fetch(extensionWebServiceUrl,
        {
          method: "POST",
          body: JSON.stringify(workflow),
          headers: { "Content-Type": "application/json" }
        });
    }
    catch (error)
    {
      communicator.sendLog(`Failed to send the prompt to the extension web service at '${extensionWebServiceUrl}'. Reason: '${error.message}'`, "error");
    }
  }

  private computePromptAndWorkflow(metadata: ImageMetadata): ComfyUiPromptAndWorkflow | undefined
  {
    if (metadata.all !== undefined)
    {
      const allMetadata = JSON.parse(metadata.all);
      try
      {
        return new ComfyUiPromptAndWorkflow(JSON.parse(allMetadata[ComfyUIConstants.prompt]), JSON.parse(allMetadata[ComfyUIConstants.workflow]));
      }
      catch (error)
      {
        // It means that the 2 ComfyUI expected metadata properties are not provided or not well-formed
      }
    }
    return undefined;
  }

}

new ComfyUiExtension().run().catch((error) =>
{
  console.error(error);
  throw error;
});
