import * as path from "node:path";
import * as fs from "node:fs";

import {
  CommandError,
  type CommandParameters,
  Communicator,
  type GenerationRecipe,
  Helper,
  type ImageFeature,
  ImageFeatureFormat,
  ImageFeatureType,
  type ImageMetadata,
  IntentDialogType,
  IntentShowType,
  PicteusExtension,
  PromptKind,
  type SettingsValue
} from "@picteus/extension-sdk";

import { ComfyUIAnalyzer, type ComfyUIAnalyzerSettings } from "./analyzers";


const ComfyUIConstants =
  {
    workflow: "workflow",
    prompt: "prompt"
  } as const;

type Json = Record<string, any>;

/**
 * The prompt and workflow of an image generated by ComfyUI.
 */
class ComfyUiPromptAndWorkflow
{

  constructor(prompt: Json, workflow: Json)
  {
    this.prompt = prompt;
    this.workflow = workflow;
  }

  readonly prompt: Json;

  readonly workflow?: Json;

}

class ComfyUiExtension extends PicteusExtension
{

  private static readonly webServiceFragment = "picteus";

  private url: string;

  private outputDirectoryPath: string;

  private inputDirectoryPath: string;

  private temporaryDirectoryPath: string;

  private extensionCurrentlyInstalled = false;

  private analyzerSettings: ComfyUIAnalyzerSettings = {};

  protected async onReady(communicator?: Communicator): Promise<void>
  {
    await this.setup(communicator!, await this.getSettings());
  }

  protected async onSettings(communicator: Communicator, value: SettingsValue): Promise<void>
  {
    await this.setup(communicator, value);
  }

  protected async onImageCreated(_communicator: Communicator, imageId: string): Promise<void>
  {
    const metadata = await this.getImageApi().imageGetMetadata({ id: imageId });
    await this.computeTags(imageId, metadata);
    await this.computeFeatures(imageId, metadata);
  }

  protected async onImageUpdated(_communicator: Communicator, imageId: string): Promise<void>
  {
    const metadata = await this.getImageApi().imageGetMetadata({ id: imageId });
    await this.computeTags(imageId, metadata);
    await this.computeFeatures(imageId, metadata);
  }

  protected async onComputeImageTags(_communicator: Communicator, imageId: string): Promise<void>
  {
    const metadata = await this.getImageApi().imageGetMetadata({ id: imageId });
    await this.computeTags(imageId, metadata);
  }

  protected async onComputeImageFeatures(_communicator: Communicator, imageId: string): Promise<void>
  {
    const metadata = await this.getImageApi().imageGetMetadata({ id: imageId });
    await this.computeFeatures(imageId, metadata);
  }

  protected async onImagesCommand(communicator: Communicator, commandId: string, imageIds: string[], _parameters: CommandParameters): Promise<void>
  {
    const imageId = imageIds[0];
    if (commandId === "openInComfyUi")
    {
      await this.openInComfyUi(communicator, imageId);
    }
    else if (commandId === "analyzeComfyUiWorkflow")
    {
      await this.analyzeComfyUiWorkflow(communicator, imageId);
    }
  }

  private async computeTags(imageId: string, metadata: ImageMetadata): Promise<void>
  {
    const promptAndWorkflow: ComfyUiPromptAndWorkflow | undefined = this.computePromptAndWorkflow(metadata);
    const tags = new Set<string>();
    if (promptAndWorkflow !== undefined)
    {
      tags.add(this.extensionId);
      const analyzer = new ComfyUIAnalyzer(promptAndWorkflow.workflow, promptAndWorkflow.prompt, this.analyzerSettings);
      for (const tag of analyzer.computeTags())
      {
        tags.add(tag);
      }
    }

    await this.getImageApi().imageSetTags({
      id: imageId,
      extensionId: this.extensionId,
      requestBody: Array.from(tags)
    });
  }

  private async computeFeatures(imageId: string, metadata: ImageMetadata): Promise<void>
  {
    const promptAndWorkflow: ComfyUiPromptAndWorkflow | undefined = this.computePromptAndWorkflow(metadata);
    if (promptAndWorkflow !== undefined)
    {
      const id = promptAndWorkflow.workflow?.["id"];
      const analyzer = new ComfyUIAnalyzer(promptAndWorkflow.workflow, promptAndWorkflow.prompt, this.analyzerSettings);
      const features: Array<ImageFeature> = [];
      const recipe: GenerationRecipe =
        {
          schemaVersion: Helper.GENERATION_RECIPE_SCHEMA_VERSION,
          modelTags: [],
          id,
          software: "comfyui",
          aspectRatio: analyzer.getAspectRatio(),
          prompt: { kind: PromptKind.Instructions, value: promptAndWorkflow }
        };
      features.push(
        {
          type: ImageFeatureType.Recipe,
          format: ImageFeatureFormat.Json,
          value: JSON.stringify(recipe)
        }
      );

      const extractedFeatures = analyzer.computeFeatures();
      for (const feature of extractedFeatures)
      {
        console.log("==========================");
        console.log(JSON.stringify(feature, null, 2));
        features.push(feature);
      }
      if (id !== undefined)
      {
        features.push({
            type: ImageFeatureType.Identity,
            format: ImageFeatureFormat.String,
            name: "id",
            value: id
          }
        );
      }

      await this.getImageApi().imageSetFeatures({
        id: imageId,
        extensionId: this.extensionId,
        imageFeature: features
      });
    }
  }

  private async analyzeComfyUiWorkflow(communicator: Communicator, imageId: string): Promise<void>
  {
    const directoryPaths = [ this.outputDirectoryPath, this.inputDirectoryPath, this.temporaryDirectoryPath ].filter((directoryPath) => directoryPath !== undefined);
    const features: Array<ImageFeature> = [];
    if (directoryPaths.length > 0)
    {
      const filePaths: string[] = [];
      const metadata = await this.getImageApi().imageGetMetadata({ id: imageId });
      const promptAndWorkflow: ComfyUiPromptAndWorkflow | undefined = this.computePromptAndWorkflow(metadata);
      if (promptAndWorkflow)
      {
        const workflow = promptAndWorkflow.workflow;
        if (workflow && Array.isArray(workflow.nodes))
        {
          for (const node of workflow.nodes)
          {
            if (node["type"] === "LoadImage" && Array.isArray(node["widgets_values"]))
            {
              const fileName: string = node["widgets_values"][0];
              for (const directoryPath of directoryPaths)
              {
                const filePath = path.join(directoryPath, fileName);
                if (fs.existsSync(filePath) === true)
                {
                  filePaths.push(filePath);
                  break;
                }
              }
            }
          }
        }
      }
      const value: string = filePaths.length === 0 ? "No image has been detected as an input image" : `The image was built on the following images: [${filePaths.map((filePath) => `'${filePath}'`).join(", ")}]`;
      features.push({
        type: ImageFeatureType.Description,
        format: ImageFeatureFormat.String,
        value
      });
      await communicator.launchIntent<void>({
        dialog: {
          type: IntentDialogType.Info,
          title: "ComfyUI Analysis",
          description: "After having inspected the image metadata, here is the output of the analysis regarding the images that were detected as input images.",
          details: `${value}.`,
          buttons: { yes: "OK" }
        }
      });
    }
  }

  private async openInComfyUi(communicator: Communicator, imageId: string): Promise<void>
  {
    if (!(this.extensionCurrentlyInstalled === true && this.url !== undefined))
    {
      throw new CommandError("Cannot open the ComfyUI workflow, because the application is not connected to the ComfyUI server");
    }
    const image = await this.getImageApi().imageGet({ id: imageId });
    const metadata = image.metadata;
    const promptAndWorkflow: ComfyUiPromptAndWorkflow | undefined = this.computePromptAndWorkflow(metadata);
    if (!promptAndWorkflow)
    {
      throw new CommandError("Cannot open the ComfyUI workflow, because prompt and workflow metadata could not be found on the image");
    }
    const workflow = promptAndWorkflow.workflow;
    if (!workflow)
    {
      throw new CommandError("Cannot open the ComfyUI workflow, because the workflow metadata could not be found on the image");
    }
    const extensionWebServiceUrl = `${this.url}/${ComfyUiExtension.webServiceFragment}/load_workflow`;
    try
    {
      await fetch(extensionWebServiceUrl,
        {
          method: "POST",
          body: JSON.stringify({ workflow, fileName: image.name }),
          headers: { "Content-Type": "application/json" }
        });
      communicator.sendLog("The workflow has been sent to ComfyUI", "debug");
    }
    catch (error)
    {
      throw new CommandError(`Failed to send the prompt to the extension web service at '${extensionWebServiceUrl}'. Reason: '${error.message}'`);
    }
    await communicator.launchIntent({ show: { type: IntentShowType.Sidebar, id: `${this.extensionId}-main` } });
  }

  private computePromptAndWorkflow(metadata: ImageMetadata): ComfyUiPromptAndWorkflow | undefined
  {
    if (metadata.all !== undefined)
    {
      const allMetadata = JSON.parse(metadata.all);
      try
      {
        const promptJson = allMetadata[ComfyUIConstants.prompt] ? JSON.parse(allMetadata[ComfyUIConstants.prompt]) : undefined;
        const workflowJson = allMetadata[ComfyUIConstants.workflow] ? JSON.parse(allMetadata[ComfyUIConstants.workflow]) : undefined;
        if (promptJson || workflowJson)
        {
          return new ComfyUiPromptAndWorkflow(promptJson, workflowJson);
        }
      }
      catch (error)
      {
        // It means that the ComfyUI metadata properties are not well-formed
      }
    }
    return undefined;
  }

  private async setup(communicator: Communicator, value: SettingsValue): Promise<void>
  {
    this.url = value["url"];
    this.analyzerSettings = {
      extractLoRAsAndAdapters: value["extractLoRAsAndAdapters"] !== undefined ? Boolean(value["extractLoRAsAndAdapters"]) : true,
      extractUpscalingAndRefinement: value["extractUpscalingAndRefinement"] !== undefined ? Boolean(value["extractUpscalingAndRefinement"]) : true,
      extractWorkflowTopology: value["extractWorkflowTopology"] !== undefined ? Boolean(value["extractWorkflowTopology"]) : true
    };

    const directoryPath = value["directoryPath"];
    if (directoryPath !== undefined)
    {
      // We guess the default ComfyUI directory paths
      this.outputDirectoryPath = path.join(directoryPath, "output");
      this.inputDirectoryPath = path.join(directoryPath, "input");
      this.temporaryDirectoryPath = path.join(directoryPath, "temp");
      const comfyUiExtensionDirectoryName = "ComfyUI-Picteus";
      const customNodesDirectoryPath = path.join(directoryPath, "custom_nodes", comfyUiExtensionDirectoryName);
      if (fs.existsSync(customNodesDirectoryPath) === false)
      {
        communicator.sendLog("Installing the ComfyUI extension", "info");
        fs.symlinkSync(path.join(PicteusExtension.getExtensionHomeDirectoryPath(), comfyUiExtensionDirectoryName), customNodesDirectoryPath, "dir");
        await communicator.launchIntent<boolean>({
          dialog: {
            type: IntentDialogType.Info,
            title: "ComfyUI extension Installed",
            description: "The extension is installed, you should now restart ComfyUi, so that it is taken into account.",
            buttons: { yes: "OK" }
          }
        });
      }
      if (this.url !== undefined)
      {
        const extensionWebServiceUrl = `${this.url}/${ComfyUiExtension.webServiceFragment}/get_directory_paths`;
        let response: Response;
        try
        {
          response = await fetch(extensionWebServiceUrl, { method: "GET" });
        }
        catch (error)
        {
          // It is very likely that the ComfyUI server is not running
          communicator.sendLog(`Failed to communicate with the ComfyUI server'. Reason: '${error.message}'`, "error");
          return;
        }
        const result = await response.text();
        if (response.ok === true)
        {
          const jsonObject = JSON.parse(result);
          this.outputDirectoryPath = jsonObject["outputDirectoryPath"];
          this.inputDirectoryPath = jsonObject["inputDirectoryPath"];
          this.temporaryDirectoryPath = jsonObject["temporaryDirectoryPath"];
        }
        else
        {
          communicator.sendLog(`Failed to retrieve the ComfyUI output directory path via the extension web service at '${extensionWebServiceUrl}'. Reason: '${result}'`, "error");
        }
      }
      this.extensionCurrentlyInstalled = true;
    }
  }

}

new ComfyUiExtension().run().catch((error) =>
{
  console.error(error);
  throw error;
});
