import "./decorators.tsp";
import "./base.tsp";
import "./modifiers.tsp";
import "./primitives.tsp";
import "./actions.tsp";
import "./escapeHatches.tsp";
import "./structures.tsp";
import "./envelope.tsp";

@doc("""
  Picteus Feature View Grammar.

  Declarative meta-model and visual grammar for describing how image features
  produced by extensions are graphically represented in the UI inspector panel.
  """)
namespace Picteus.FeatureViewGrammar;
