import "./decorators.tsp";
import "./base.tsp";
import "./modifiers.tsp";
import "./primitives.tsp";
import "./actions.tsp";
import "./escapeHatches.tsp";
import "./structures.tsp";
import "./envelope.tsp";

@doc("""
  Picteus ViewKit.

  Declarative UI specification and visual component kit for representing structured
  entity data, metrics, layouts, and interactive actions.
  """)
namespace Picteus.ViewKit;
