emit:
  - "@typespec/json-schema"
  - "@picteus/specification-factory"

options:
  "@typespec/json-schema":
    emitter-output-dir: "{project-root}/dist/schema"
    file-type: "json"
    bundleId: "specification-factory.json"
    polymorphic-models-strategy: "oneOf"
  "@picteus/specification-factory":
    emitter-output-dir: "{project-root}/dist"
    targets:
      - "typescript"
      - "python"
      - "react"
