import { ApiProperty, ApiSchema } from "@nestjs/swagger";

import {
  alphaNumericPlusPattern,
  applicationXGzipMimeType,
  attachmentUriPrefix,
  attachmentUriSchema,
  computeImageFormatsExtensions,
  Dates,
  extensionIdSchema,
  FieldLengths,
  fileWithProtocol,
  fromMimeType,
  ImageFeatureFormat,
  ImageFeatureType,
  ImageFeatureValue,
  ImageFormat,
  ImageFormats,
  imageIdSchema,
  ImageTag,
  imageUrlSchema,
  integerIdSchema,
  NumericRange,
  repositoryIdSchema,
  shortTechnicalSchema,
  technicalSchema,
  toFileExtension,
  toMimeType
} from "./common.dtos";
import {
  CommandEntity,
  ConfigurationCapability,
  ConfigurationExtensionCommand,
  Extension,
  ExtensionActivities,
  ExtensionActivity,
  ExtensionActivityKind,
  ExtensionAndManual,
  ExtensionGenerationOptions,
  ExtensionManual,
  ExtensionsConfiguration,
  ExtensionSettings,
  ExtensionStatus,
  Manifest,
  ManifestCapability,
  ManifestCapabilityId,
  ManifestEvent,
  ManifestExecution,
  ManifestExtensionCommand,
  ManifestInstructions,
  ManifestRuntimeEnvironment,
  ManifestUserInterface,
  UserInterfaceAnchor
} from "./extension.dtos";
import {
  SearchCriteria,
  SearchFeatureComparisonOperator,
  SearchFeatureCondition,
  SearchFeatureLogicalOperator,
  SearchFeatures,
  SearchFilter,
  SearchImagesOrigin,
  SearchKeyword,
  SearchOriginKind,
  SearchProperties,
  SearchPropertyRange,
  SearchRepositoriesOrigin,
  SearchSorting,
  SearchSortingProperty,
  SearchTags
} from "./search.dtos";
import {
  Repository,
  RepositoryActivities,
  RepositoryActivity,
  RepositoryActivityKind,
  RepositoryList,
  RepositoryLocation,
  RepositoryLocationType,
  RepositoryStatus
} from "./repository.dtos";
import { Collection } from "./collection.dtos";
import {
  AllExtensionImageFeatureNames,
  AllExtensionImageTags,
  AllImageEmbeddings,
  AllImageFeatures,
  ApplicationMetadata,
  ApplicationMetadataItem,
  ApplicationMetadataItemFreeValue,
  ComputedImageFormat,
  ExtensionImageEmbeddings,
  ExtensionImageFeature,
  ExtensionImageFeatureName,
  ExtensionImageTag,
  GenerationRecipe,
  Image,
  ImageDimensions,
  ImageDistance,
  ImageDistances,
  ImageEmbeddings,
  ImageFeature,
  ImageFeatureNullValue,
  ImageMediaUrl,
  ImageMetadata,
  ImageResizeRender,
  ImageSummary,
  InstructionsPrompt,
  PromptKind,
  SearchFeaturesResult,
  SearchImageResult,
  SearchImageSummaryResult,
  SearchMediaUrlResult,
  SearchParameters,
  SearchRange,
  SearchTagsResult,
  TextualPrompt
} from "./image.dtos";
import { apiScopesSeparator, ApiSecret, ApiSecretSummary, ApiSecretType } from "./apiSecret.dtos";
import { Settings } from "./miscellaneous.dtos";


/**
 * The name of the software.
 */
enum Software
{
  picteus = "picteus"
}

@ApiSchema({ description: "Contains the definition of all the application constants" })
class ConstantsRegistry
{

  @ApiProperty({
    description: "The application name",
    enum: Software,
    enumName: "Software",
    required: true
  })
  applicationName: Software = Software.picteus;

  @ApiProperty({
    description: "The value to pass to the image search web services to designate a 'non-null' feature value",
    enum: ImageFeatureNullValue,
    enumName: "ImageFeatureNullValue",
    required: true
  })
  imageFeatureNullValue: ImageFeatureNullValue = ImageFeatureNullValue.Null;

}

export {
  AllExtensionImageFeatureNames,
  AllExtensionImageTags,
  AllImageEmbeddings,
  AllImageFeatures,
  alphaNumericPlusPattern,
  ApiSecret,
  ApiSecretSummary,
  ApiSecretType,
  apiScopesSeparator,
  ApplicationMetadata,
  ApplicationMetadataItem,
  ApplicationMetadataItemFreeValue,
  applicationXGzipMimeType,
  attachmentUriPrefix,
  attachmentUriSchema,
  Collection,
  CommandEntity,
  ComputedImageFormat,
  computeImageFormatsExtensions,
  ConfigurationCapability,
  ConfigurationExtensionCommand,
  ConstantsRegistry,
  Dates,
  Extension,
  ExtensionActivities,
  ExtensionActivity,
  ExtensionActivityKind,
  ExtensionAndManual,
  ExtensionsConfiguration,
  ExtensionGenerationOptions,
  extensionIdSchema,
  ExtensionImageEmbeddings,
  ExtensionImageFeature,
  ExtensionImageFeatureName,
  ExtensionImageTag,
  ExtensionManual,
  ExtensionStatus,
  ExtensionSettings,
  FieldLengths,
  fileWithProtocol,
  fromMimeType,
  GenerationRecipe,
  Image,
  ImageDimensions,
  ImageDistance,
  ImageDistances,
  ImageEmbeddings,
  ImageFeature,
  ImageFeatureFormat,
  ImageFeatureNullValue,
  ImageFeatureType,
  ImageFeatureValue,
  ImageFormat,
  ImageFormats,
  imageIdSchema,
  ImageMediaUrl,
  ImageMetadata,
  ImageResizeRender,
  SearchImageResult,
  ImageSummary,
  SearchImageSummaryResult,
  ImageTag,
  imageUrlSchema,
  InstructionsPrompt,
  integerIdSchema,
  Manifest,
  ManifestCapability,
  ManifestCapabilityId,
  ManifestEvent,
  ManifestExtensionCommand,
  ManifestExecution,
  ManifestInstructions,
  ManifestRuntimeEnvironment,
  ManifestUserInterface,
  NumericRange,
  PromptKind,
  Repository,
  RepositoryActivity,
  RepositoryActivityKind,
  RepositoryActivities,
  repositoryIdSchema,
  RepositoryList,
  RepositoryLocation,
  RepositoryLocationType,
  RepositoryStatus,
  SearchCriteria,
  SearchFeatureCondition,
  SearchFeatureComparisonOperator,
  SearchFeatureLogicalOperator,
  SearchFeaturesResult,
  SearchFeatures,
  SearchFilter,
  SearchImagesOrigin,
  SearchKeyword,
  SearchMediaUrlResult,
  SearchOriginKind,
  SearchParameters,
  SearchProperties,
  SearchPropertyRange,
  SearchRange,
  SearchRepositoriesOrigin,
  SearchSorting,
  SearchSortingProperty,
  SearchTagsResult,
  SearchTags,
  Settings,
  shortTechnicalSchema,
  Software,
  technicalSchema,
  TextualPrompt,
  toFileExtension,
  toMimeType,
  UserInterfaceAnchor
};
