import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";


const sidebars: SidebarsConfig =
  {
    setupSidebar: [
      "setup/install",
      "setup/start",
      "setup/files",
      "setup/traces"
    ],
    manualSidebar: [
      "manual/webservicesapi",
      "manual/databases",
      "manual/facets",
      "manual/tags",
      "manual/features",
      "manual/embedding",
      "manual/container"
    ],
    developerSidebar: [{ type: "autogenerated", dirName: "developer" }],
    extensionsSidebar: [
      "extensions/guide",
      {
        type: "category",
        label: "Reference",
        link: {
          type: "generated-index",
          description: "Technical reference documentation for Picteus extensions."
        },
        items: [
          "extensions/reference/overview",
          "extensions/reference/manifest",
          "extensions/reference/class",
          "extensions/reference/api",
          "extensions/reference/viewkit",
          "extensions/reference/intents",
          "extensions/reference/manual"
        ]
      },
      "extensions/unpacked"
    ]
  };

export default sidebars;
