import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";


const sidebars: SidebarsConfig =
  {
    setupSidebar: [
      "setup",
      "setup/install",
      "setup/start",
      "setup/files",
      "setup/traces",
      "setup/troubleshooting"
    ],
    manualSidebar: [
      "manual",
      {
        type: "category",
        label: "Web services API",
        link: {
          type: "doc",
          id: "manual/webservicesapi/index"
        },
        items: [
          "manual/webservicesapi/images",
          "manual/webservicesapi/repositories",
          "manual/webservicesapi/collections",
          "manual/webservicesapi/extensions",
          "manual/webservicesapi/image-attachments",
          "manual/webservicesapi/api-secrets",
          "manual/webservicesapi/settings",
          "manual/webservicesapi/administration",
          "manual/webservicesapi/miscellaneous"
        ]
      },
      "manual/databases",
      "manual/facets",
      "manual/tags",
      "manual/features",
      "manual/embedding",
      "manual/container"
    ],
    developerSidebar: [
      "developer",
      {
        type: "autogenerated",
        dirName: "developer"
      }
    ],
    extensionsSidebar: [
      "extensions",
      "extensions/guide",
      {
        type: "category",
        label: "Reference",
        link: {
          type: "generated-index",
          description: "Technical reference documentation for Picteus extensions."
        },
        items: [
          "extensions/reference/overview",
          "extensions/reference/manifest",
          "extensions/reference/class",
          "extensions/reference/api",
          "extensions/reference/viewkit",
          "extensions/reference/intents",
          "extensions/reference/manual"
        ]
      },
      "extensions/unpacked"
    ]
  };

export default sidebars;
