import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";


const sidebars: SidebarsConfig =
  {
    setupSidebar: [
      "setup/install",
      "setup/start",
      "setup/files"
    ],
    manualSidebar: [
      "manual/webservicesapi",
      "manual/databases",
      "manual/container"
    ],
    developerSidebar: [{ type: "autogenerated", dirName: "developer" }],
    extensionsSidebar: [
      "extensions/guide",
      {
        type: "category",
        label: "Reference",
        link: {
          type: "generated-index",
          description: "Technical reference documentation for Picteus extensions."
        },
        items: [
          "extensions/reference/overview",
          "extensions/reference/intents"
        ]
      },
      "extensions/unpacked"
    ]
  };

export default sidebars;
