import { GrammarModel, GrammarProperty, GrammarSpec, GrammarType } from "./typespecModel.js";


const SCHEMA_VERSION_PROPERTY = "schemaVersion";
const SCHEMA_VERSION_VALUE = "1.0";
const DISCRIMINATOR_PROPERTY = "type";
const ELEMENTS_PROPERTY = "elements";
const ELEMENT_SUFFIX = "Element";
const RECORD_TYPE = "Record<string, unknown>";

const BUILDER_RETURN_DESCRIPTION = "This builder instance for method chaining.";
const COMPACT_JSON_RETURN_DESCRIPTION = "Compact JSON string without indentation.";

const GENERATED_FILE_HEADER = [
  "// ---------------------------------------------------------------------------",
  "// Auto-generated by @picteus/feature-view-grammar emitter. Do not edit directly.",
  "// ---------------------------------------------------------------------------"
];
const CONCRETE_CLASSES_SECTION_HEADER = "// --- Concrete Model Classes Implementing Interfaces ---";
const FUNCTIONAL_FACTORIES_SECTION_HEADER = "// --- Functional DSL Factory Helpers ---";
const TYPE_GUARDS_SECTION_HEADER = "// --- Type Guards ---";


export interface TsDocParam
{

  name: string;
  description?: string;

}

export interface TsDocOptions
{

  summary?: string;
  remarks?: string;
  params?: TsDocParam[];
  returns?: string;
  defaultValue?: string;
  example?: string;
  indent?: string;

}

interface PropertyPartition
{

  readonly nonTypeProperties: GrammarProperty[];
  readonly requiredProperties: GrammarProperty[];
  readonly optionalProperties: GrammarProperty[];
  readonly arrayProperties: GrammarProperty[];
  readonly scalarRequiredProperties: GrammarProperty[];
  readonly scalarOptionalProperties: GrammarProperty[];

}

function formatTsDoc(options: TsDocOptions): string
{
  const indent = options.indent ?? "";
  const rawLines: string[] = [];

  if (options.summary)
  {
    const summaryLines = options.summary.trim().split("\n");
    rawLines.push(
      ...summaryLines.map(
        (line) =>
        {
          return line.trim();
        }
      )
    );
  }

  if (options.remarks)
  {
    if (rawLines.length > 0)
    {
      rawLines.push("");
    }
    rawLines.push("@remarks");
    const remarkLines = options.remarks.trim().split("\n");
    rawLines.push(
      ...remarkLines.map(
        (line) =>
        {
          return line.trim();
        }
      )
    );
  }

  if (options.defaultValue !== undefined)
  {
    if (rawLines.length > 0)
    {
      rawLines.push("");
    }
    rawLines.push(`@defaultValue ${options.defaultValue}`);
  }

  if (options.params && options.params.length > 0)
  {
    if (rawLines.length > 0)
    {
      rawLines.push("");
    }
    for (const parameter of options.params)
    {
      const description = parameter.description ? ` - ${parameter.description.trim()}` : "";
      rawLines.push(`@param ${parameter.name}${description}`);
    }
  }

  if (options.returns)
  {
    if (rawLines.length > 0 && (!options.params || options.params.length === 0))
    {
      rawLines.push("");
    }
    rawLines.push(`@returns ${options.returns}`);
  }

  if (options.example)
  {
    if (rawLines.length > 0)
    {
      rawLines.push("");
    }
    rawLines.push("@example", "```typescript", options.example.trim(), "```");
  }

  if (rawLines.length === 0)
  {
    return "";
  }

  if (rawLines.length === 1 && !rawLines[0].startsWith("@"))
  {
    return `${indent}/** ${rawLines[0]} */`;
  }

  const formattedLines = rawLines.map(
    (line) =>
    {
      return line === "" ? `${indent} *` : `${indent} * ${line}`;
    }
  );
  return `${indent}/**\n${formattedLines.join("\n")}\n${indent} */`;
}

function resolveTsType(type: GrammarType): string
{
  switch (type.kind)
  {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "literal":
      return type.name;
    case "enum":
      return type.name;
    case "model":
      return type.name;
    case "array":
    {
      const element = resolveTsType(type.elementType ?? { kind: "unknown", name: "unknown" });
      return type.elementType?.kind === "union" ? `(${element})[]` : `${element}[]`;
    }
    case "record":
      return RECORD_TYPE;
    case "union":
      return type.unionTypes?.map(resolveTsType).join(" | ") ?? type.name;
    default:
      return "unknown";
  }
}

function capitalizeText(text: string): string
{
  return text.charAt(0).toUpperCase() + text.slice(1);
}

function getFactoryNames(model: GrammarModel): { primary: string; aliases: string[] }
{
  let baseName = model.name;
  if (baseName.endsWith(ELEMENT_SUFFIX))
  {
    baseName = baseName.slice(0, -ELEMENT_SUFFIX.length);
  }
  const primary = baseName.charAt(0).toLowerCase() + baseName.slice(1);
  return { primary, aliases: model.aliases ?? [] };
}

function partitionProperties(
  properties: GrammarProperty[],
  options?: { excludeSchemaVersion?: boolean }
): PropertyPartition
{
  const nonTypeProperties = properties.filter(
    (property) =>
    {
      return (
        property.name !== DISCRIMINATOR_PROPERTY &&
        (!options?.excludeSchemaVersion || property.name !== SCHEMA_VERSION_PROPERTY)
      );
    }
  );
  const requiredProperties = nonTypeProperties.filter(
    (property) =>
    {
      return !property.optional && property.defaultValue === undefined;
    }
  );
  const optionalProperties = nonTypeProperties.filter(
    (property) =>
    {
      return property.optional || property.defaultValue !== undefined;
    }
  );
  const arrayProperties = nonTypeProperties.filter(
    (property) =>
    {
      return property.type.kind === "array";
    }
  );
  const scalarRequiredProperties = requiredProperties.filter(
    (property) =>
    {
      return property.type.kind !== "array";
    }
  );
  const scalarOptionalProperties = optionalProperties.filter(
    (property) =>
    {
      return property.type.kind !== "array";
    }
  );

  return {
    nonTypeProperties,
    requiredProperties,
    optionalProperties,
    arrayProperties,
    scalarRequiredProperties,
    scalarOptionalProperties
  };
}

function formatTsDefaultValue(property: GrammarProperty): string | undefined
{
  if (property.defaultValue === undefined)
  {
    return undefined;
  }
  if (property.type.kind === "enum")
  {
    return `${property.type.name}.${property.defaultValue}`;
  }
  if (property.type.kind === "string" || typeof property.defaultValue === "string")
  {
    return `"${property.defaultValue}"`;
  }
  if (typeof property.defaultValue === "boolean")
  {
    return property.defaultValue ? "true" : "false";
  }
  return String(property.defaultValue);
}

function formatOptionsParameter(
  optionalProperties: GrammarProperty[],
  docDescription = "Optional component settings."
): { parameter: string; docParam?: TsDocParam }
{
  if (optionalProperties.length === 0)
  {
    return { parameter: "" };
  }
  const optionalFields = optionalProperties
    .map(
      (property) =>
      {
        return `${property.name}?: ${resolveTsType(property.type)}`;
      }
    )
    .join("; ");

  const optionalDescriptions = optionalProperties
    .map(
      (property) =>
      {
        const defaultValueSuffix = property.defaultValue !== undefined ? ` (defaults to \`${property.defaultValue}\`)` : "";
        return `${property.name}${defaultValueSuffix}`;
      }
    )
    .join(", ");

  return {
    parameter: `options?: { ${optionalFields} }`,
    docParam: {
      name: "options",
      description: docDescription.includes("(") ? docDescription : `${docDescription} (${optionalDescriptions}).`
    }
  };
}

function formatClassInvocationArgs(
  requiredProperties: GrammarProperty[],
  arrayProperties: GrammarProperty[],
  optionalProperties: GrammarProperty[],
  mode: "builder" | "params" | "helper"
): string[]
{
  const args: string[] = [];
  const requiredArrays = arrayProperties.filter((property) => !property.optional);
  const optionalArrays = arrayProperties.filter((property) => property.optional);

  for (const property of requiredProperties)
  {
    if (mode === "builder")
    {
      args.push(`this._${property.name}`);
    }
    else if (mode === "params")
    {
      args.push(`params.${property.name}`);
    }
    else
    {
      args.push(property.name);
    }
  }

  for (const property of requiredArrays)
  {
    if (mode === "builder")
    {
      args.push(`this._${property.name}`);
    }
    else if (mode === "params")
    {
      args.push(`params.${property.name}`);
    }
    else
    {
      args.push(`options?.${property.name} ?? []`);
    }
  }

  const optEntries: string[] = [];
  for (const property of optionalProperties)
  {
    if (mode === "builder")
    {
      optEntries.push(`${property.name}: this._${property.name}`);
    }
    else if (mode === "params")
    {
      optEntries.push(`${property.name}: params.${property.name}`);
    }
    else
    {
      optEntries.push(`${property.name}: options?.${property.name}`);
    }
  }

  for (const property of optionalArrays)
  {
    if (mode === "builder")
    {
      optEntries.push(`${property.name}: this._${property.name}.length > 0 ? this._${property.name} : undefined`);
    }
    else if (mode === "params")
    {
      optEntries.push(`${property.name}: params.${property.name}`);
    }
    else
    {
      optEntries.push(`${property.name}: options?.${property.name}`);
    }
  }

  if (optEntries.length > 0)
  {
    const indent = mode === "helper" ? "      " : "        ";
    args.push(`{\n${indent}${optEntries.join(`,\n${indent}`)}\n${mode === "helper" ? "    " : "      "}}`);
  }

  return args;
}

function generateModelPropertyChecks(
  properties: GrammarProperty[],
  spec: GrammarSpec,
  targetVariable: string = "element"
): string[]
{
  const propertyChecks: string[] = [];
  for (const property of properties)
  {
    if (property.name === DISCRIMINATOR_PROPERTY || property.name === SCHEMA_VERSION_PROPERTY)
    {
      continue;
    }
    const check = generateDeepTypeCheck(`${targetVariable}.${property.name}`, property.type, spec);
    if (property.optional || property.defaultValue !== undefined)
    {
      propertyChecks.push(`(${targetVariable}.${property.name} === undefined || ${check})`);
    }
    else
    {
      propertyChecks.push(`("${property.name}" in value && ${check})`);
    }
  }
  return propertyChecks;
}

function generateModelFactory(model: GrammarModel): string[]
{
  const lines: string[] = [];
  const { primary, aliases } = getFactoryNames(model);
  const { requiredProperties, optionalProperties } = partitionProperties(model.properties);

  const parameters: string[] = [];
  const docParameters: TsDocParam[] = [];

  for (const property of requiredProperties)
  {
    parameters.push(`${property.name}: ${resolveTsType(property.type)}`);
    docParameters.push({ name: property.name, description: property.doc });
  }

  const {
    parameter: optionsParam,
    docParam: optionsDocParam
  } = formatOptionsParameter(optionalProperties, "Optional settings");
  if (optionsParam)
  {
    parameters.push(optionsParam);
    if (optionsDocParam)
    {
      docParameters.push(optionsDocParam);
    }
  }

  const allNames = Array.from(new Set([ primary, ...aliases ]));

  for (const functionName of allNames)
  {
    lines.push(
      formatTsDoc(
        {
          summary: `Creates a \`${model.name}\` component instance.`,
          remarks: model.doc,
          params: docParameters,
          returns: `A strongly-typed \`${model.name}\` object.`
        }
      )
    );
    lines.push(`export function ${functionName}(${parameters.join(", ")}): ${model.name}`);
    lines.push("{");
    lines.push("  return {");

    if (model.discriminatorValue)
    {
      lines.push(`    ${DISCRIMINATOR_PROPERTY}: "${model.discriminatorValue}",`);
    }

    for (const property of requiredProperties)
    {
      if (property.type.kind === "array")
      {
        lines.push(`    ${property.name}: [ ...${property.name} ],`);
      }
      else
      {
        lines.push(`    ${property.name},`);
      }
    }

    for (const property of optionalProperties)
    {
      const defaultValue = formatTsDefaultValue(property);
      if (defaultValue !== undefined)
      {
        lines.push(`    ${property.name}: options?.${property.name} ?? ${defaultValue},`);
      }
      else if (property.type.kind === "array")
      {
        lines.push(`    ${property.name}: options?.${property.name} ? [ ...options.${property.name} ] : undefined,`);
      }
      else
      {
        lines.push(`    ${property.name}: options?.${property.name},`);
      }
    }

    const lastIndex = lines.length - 1;
    lines[lastIndex] = lines[lastIndex].replace(/,$/, "");

    lines.push("  };");
    lines.push("}");
    lines.push("");
  }

  return lines;
}

function generateModelClass(model: GrammarModel, polymorphicRootNames: ReadonlySet<string>): string[]
{
  const lines: string[] = [];
  const className = `${model.name}Class`;
  const baseClass = (model.baseModelName && polymorphicRootNames.has(model.baseModelName))
    ? `Base${model.baseModelName}<${model.name}>`
    : `GrammarNode<${model.name}>`;

  const { requiredProperties, optionalProperties } = partitionProperties(model.properties);

  lines.push(
    formatTsDoc(
      {
        summary: `Class implementation of the \`${model.name}\` interface.`,
        remarks: model.doc
      }
    )
  );
  lines.push(`export class ${className} extends ${baseClass} implements ${model.name}`);
  lines.push("{");

  if (model.discriminatorValue)
  {
    lines.push(
      formatTsDoc(
        {
          summary: "The discriminator type tag.",
          defaultValue: `"${model.discriminatorValue}"`,
          indent: "  "
        }
      )
    );
    lines.push(`  readonly ${DISCRIMINATOR_PROPERTY} = "${model.discriminatorValue}" as const;`);
  }

  for (const property of requiredProperties)
  {
    lines.push(formatTsDoc({ summary: property.doc, indent: "  " }));
    lines.push(`  readonly ${property.name}: ${resolveTsType(property.type)};`);
  }

  for (const property of optionalProperties)
  {
    const defaultValueString = formatTsDefaultValue(property);
    lines.push(formatTsDoc({ summary: property.doc, defaultValue: defaultValueString, indent: "  " }));
    const optional = property.optional ? "?" : "";
    lines.push(`  readonly ${property.name}${optional}: ${resolveTsType(property.type)};`);
  }
  lines.push("");

  const constructorParameters: string[] = [];
  const constructorDocParameters: TsDocParam[] = [];

  for (const property of requiredProperties)
  {
    constructorParameters.push(`${property.name}: ${resolveTsType(property.type)}`);
    constructorDocParameters.push({ name: property.name, description: property.doc });
  }

  const {
    parameter: optionsParam,
    docParam: optionsDocParam
  } = formatOptionsParameter(optionalProperties, "Optional property overrides");
  if (optionsParam)
  {
    constructorParameters.push(optionsParam);
    if (optionsDocParam)
    {
      constructorDocParameters.push(optionsDocParam);
    }
  }

  lines.push(
    formatTsDoc(
      {
        summary: `Initializes a new \`${className}\` instance.`,
        params: constructorDocParameters,
        indent: "  "
      }
    )
  );
  lines.push(`  constructor(${constructorParameters.join(", ")})`);
  lines.push("  {");
  lines.push("    super();");

  for (const property of requiredProperties)
  {
    if (property.type.kind === "array")
    {
      lines.push(`    this.${property.name} = ${property.name} ? [ ...${property.name} ] : [];`);
    }
    else
    {
      lines.push(`    this.${property.name} = ${property.name};`);
    }
  }

  for (const property of optionalProperties)
  {
    const defaultValue = formatTsDefaultValue(property);
    if (defaultValue !== undefined)
    {
      lines.push(`    this.${property.name} = options?.${property.name} ?? ${defaultValue};`);
    }
    else if (property.type.kind === "array")
    {
      lines.push(`    this.${property.name} = options?.${property.name} ? [ ...options.${property.name} ] : undefined;`);
    }
    else
    {
      lines.push(`    this.${property.name} = options?.${property.name};`);
    }
  }
  lines.push("  }");
  lines.push("}");
  lines.push("");

  return lines;
}

export function generateTypeScriptCode(spec: GrammarSpec): string
{
  const lines: string[] = [];
  const polymorphicRootNames = new Set(
    spec.polymorphicRoots.map(
      (root) =>
      {
        return root.name;
      }
    )
  );

  lines.push(...GENERATED_FILE_HEADER);
  lines.push("");

  // We define the generic base serialization class
  lines.push(
    formatTsDoc(
      {
        summary: "Generic base class providing recursive JSON serialization for all model instances."
      }
    )
  );
  lines.push("export abstract class GrammarNode<T = unknown>");
  lines.push("{");
  lines.push(
    formatTsDoc(
      {
        summary: "Serializes this model instance into a strongly-typed, JSON-compatible plain object.",
        returns: "The plain object representation conforming to interface `T`.",
        indent: "  "
      }
    )
  );
  lines.push("  toJSON(): T");
  lines.push("  {");
  lines.push("    const result: Record<string, unknown> = {};");
  lines.push("    for (const [key, value] of Object.entries(this))");
  lines.push("    {");
  lines.push("      if (value !== undefined)");
  lines.push("      {");
  lines.push("        if (Array.isArray(value))");
  lines.push("        {");
  lines.push("          result[key] = value.map(");
  lines.push("            (item) =>");
  lines.push("            {");
  lines.push("              return item && typeof item === \"object\" && typeof (item as { toJSON?: () => unknown }).toJSON === \"function\"");
  lines.push("                ? (item as { toJSON: () => unknown }).toJSON()");
  lines.push("                : item;");
  lines.push("            }");
  lines.push("          );");
  lines.push("        }");
  lines.push("        else if (value && typeof value === \"object\" && typeof (value as { toJSON?: () => unknown }).toJSON === \"function\")");
  lines.push("        {");
  lines.push("          result[key] = (value as { toJSON: () => unknown }).toJSON();");
  lines.push("        }");
  lines.push("        else");
  lines.push("        {");
  lines.push("          result[key] = value;");
  lines.push("        }");
  lines.push("      }");
  lines.push("    }");
  lines.push("    return result as T;");
  lines.push("  }");
  lines.push("");
  lines.push("  /**");
  lines.push("   * Returns the compact JSON string representation of this model instance with no indentation.");
  lines.push("   *");
  lines.push(`   * @returns ${COMPACT_JSON_RETURN_DESCRIPTION}`);
  lines.push("   */");
  lines.push("  toString(): string");
  lines.push("  {");
  lines.push("    return JSON.stringify(this.toJSON());");
  lines.push("  }");
  lines.push("}");
  lines.push("");

  // 1. We generate Enums from AST
  for (const grammarEnum of spec.enums)
  {
    lines.push(formatTsDoc({ summary: grammarEnum.doc }));
    lines.push(`export enum ${grammarEnum.name}`);
    lines.push("{");
    for (const member of grammarEnum.members)
    {
      lines.push(formatTsDoc({ summary: member.doc, indent: "  " }));
      lines.push(`  ${member.name} = "${member.value}",`);
    }
    if (grammarEnum.members.length > 0)
    {
      const lastIndex = lines.length - 1;
      lines[lastIndex] = lines[lastIndex].replace(/,$/, "");
    }
    lines.push("}");
    lines.push("");
  }

  // 2. We generate Base Interfaces and Abstract Base Classes for Polymorphic Roots
  for (const root of spec.polymorphicRoots)
  {
    const rootModel = spec.models.find(
      (model) =>
      {
        return model.name === root.name;
      }
    );
    lines.push(
      formatTsDoc(
        {
          summary: root.doc ?? `Base structural contract for all \`${root.name}\` visual element models.`
        }
      )
    );
    lines.push(`export interface ${root.name}Base`);
    lines.push("{");
    lines.push(
      formatTsDoc(
        {
          summary: "The polymorphic discriminator type tag.",
          indent: "  "
        }
      )
    );
    lines.push(`  readonly ${root.discriminatorProperty}: string;`);
    if (rootModel)
    {
      for (const property of rootModel.properties)
      {
        if (property.name !== root.discriminatorProperty)
        {
          lines.push(formatTsDoc({ summary: property.doc, indent: "  " }));
          const optional = property.optional ? "?" : "";
          lines.push(`  readonly ${property.name}${optional}: ${resolveTsType(property.type)};`);
        }
      }
    }
    lines.push("}");
    lines.push("");

    lines.push(
      formatTsDoc(
        {
          summary: `Abstract base class for all \`${root.name}\` models.`
        }
      )
    );
    lines.push(`export abstract class Base${root.name}<T = ${root.name}> extends GrammarNode<T> implements ${root.name}Base`);
    lines.push("{");
    lines.push(`  abstract readonly ${root.discriminatorProperty}: string;`);
    if (rootModel)
    {
      for (const property of rootModel.properties)
      {
        if (property.name !== root.discriminatorProperty)
        {
          const optional = property.optional ? "?" : "";
          lines.push(`  abstract readonly ${property.name}${optional}: ${resolveTsType(property.type)};`);
        }
      }
    }
    lines.push("}");
    lines.push("");
  }

  // 3. We generate Interfaces for all concrete models with materialized inheritance
  for (const model of spec.models)
  {
    if (polymorphicRootNames.has(model.name) || model.isDslIgnored)
    {
      continue;
    }
    const extendsClause = model.baseModelName
      ? (polymorphicRootNames.has(model.baseModelName) ? ` extends ${model.baseModelName}Base` : ` extends ${model.baseModelName}`)
      : "";
    lines.push(formatTsDoc({ summary: model.doc }));
    lines.push(`export interface ${model.name}${extendsClause}`);
    lines.push("{");
    for (const property of model.properties)
    {
      let defaultValueString: string | undefined;
      if (property.name === DISCRIMINATOR_PROPERTY && model.discriminatorValue)
      {
        defaultValueString = `"${model.discriminatorValue}"`;
      }
      else if (property.defaultValue !== undefined)
      {
        defaultValueString = formatTsDefaultValue(property);
      }
      lines.push(formatTsDoc({ summary: property.doc, defaultValue: defaultValueString, indent: "  " }));
      const optional = property.optional ? "?" : "";
      const tsType = resolveTsType(property.type);
      lines.push(`  readonly ${property.name}${optional}: ${tsType};`);
    }
    lines.push("}");
    lines.push("");
  }

  // 4. We generate Discriminated Union Types dynamically from AST polymorphic roots
  for (const root of spec.polymorphicRoots)
  {
    const unionTypes = root.derivedModels
      .map(
        (derivedModel) =>
        {
          return derivedModel.name;
        }
      )
      .join(" | ");
    lines.push(
      formatTsDoc(
        {
          summary: root.doc ?? `Polymorphic discriminated union of all concrete \`${root.name}\` models.`
        }
      )
    );
    lines.push(`export type ${root.name} = ${unionTypes};`);
    lines.push("");
  }

  // 5. We generate Classes implementing the Interfaces
  lines.push(CONCRETE_CLASSES_SECTION_HEADER);
  lines.push("");
  for (const model of spec.models)
  {
    if (polymorphicRootNames.has(model.name) || model.isDslIgnored)
    {
      continue;
    }
    const classLines = generateModelClass(model, polymorphicRootNames);
    lines.push(...classLines);
  }

  // 6. We generate Model-Driven Fluent Builders for all @dslRoot models
  const rootModels = spec.rootModels.length > 0 ? spec.rootModels : (spec.rootModel ? [ spec.rootModel ] : []);
  for (const root of rootModels)
  {
    const builderClassName = `${root.name}Builder`;
    const {
      nonTypeProperties: rootNonTypeProperties,
      scalarRequiredProperties: rootRequiredProperties,
      scalarOptionalProperties: rootOptionalProperties,
      arrayProperties: rootArrayProperties
    } = partitionProperties(root.properties, { excludeSchemaVersion: true });

    lines.push(
      formatTsDoc(
        {
          summary: `Fluent builder for constructing strongly-typed \`${root.name}\` instances.`,
          remarks: root.doc
        }
      )
    );
    lines.push(`export class ${builderClassName}`);
    lines.push("{");

    for (const property of rootRequiredProperties)
    {
      lines.push(`  private readonly _${property.name}: ${resolveTsType(property.type)};`);
    }
    for (const property of rootOptionalProperties)
    {
      lines.push(`  private _${property.name}?: ${resolveTsType(property.type)};`);
    }
    for (const property of rootArrayProperties)
    {
      const elementType = resolveTsType(property.type.elementType ?? { kind: "unknown", name: "unknown" });
      lines.push(`  private readonly _${property.name}: ${elementType}[] = [];`);
    }
    if (rootRequiredProperties.length > 0 || rootOptionalProperties.length > 0 || rootArrayProperties.length > 0)
    {
      lines.push("");
    }

    const constructorArguments = rootRequiredProperties
      .map(
        (property) =>
        {
          return `${property.name}: ${resolveTsType(property.type)}`;
        }
      )
      .join(", ");
    const constructorDocParameters: TsDocParam[] = rootRequiredProperties.map(
      (property) =>
      {
        return { name: property.name, description: property.doc };
      }
    );

    lines.push(
      formatTsDoc(
        {
          summary: `Initializes a new \`${builderClassName}\`.`,
          params: constructorDocParameters,
          indent: "  "
        }
      )
    );
    lines.push(`  constructor(${constructorArguments})`);
    lines.push("  {");
    for (const property of rootRequiredProperties)
    {
      lines.push(`    this._${property.name} = ${property.name};`);
    }
    lines.push("  }");
    lines.push("");

    // We generate setters for scalar optional properties
    for (const property of rootOptionalProperties)
    {
      lines.push(
        formatTsDoc(
          {
            summary: `Sets the \`${property.name}\` property on this builder.`,
            params: [ { name: property.name, description: property.doc } ],
            returns: BUILDER_RETURN_DESCRIPTION,
            indent: "  "
          }
        )
      );
      lines.push(`  ${property.name}(${property.name}: ${resolveTsType(property.type)}): this`);
      lines.push("  {");
      lines.push(`    this._${property.name} = ${property.name};`);
      lines.push("    return this;");
      lines.push("  }");
      lines.push("");
    }

    // We generate collection adders for array properties
    for (const property of rootArrayProperties)
    {
      const elementType = resolveTsType(property.type.elementType ?? { kind: "unknown", name: "unknown" });
      const singularName = property.name.endsWith("s") ? property.name.slice(0, -1) : property.name;
      const addMethodName = `add${capitalizeText(singularName)}`;
      const addAllMethodName = `add${capitalizeText(property.name)}`;

      if (property.name === ELEMENTS_PROPERTY)
      {
        lines.push(
          formatTsDoc(
            {
              summary: "Appends a visual element.",
              params: [ { name: "element", description: "The visual UI element component to add." } ],
              returns: BUILDER_RETURN_DESCRIPTION,
              indent: "  "
            }
          )
        );
        lines.push(`  add(element: ${elementType}): this`);
        lines.push("  {");
        lines.push(`    this._${property.name}.push(element);`);
        lines.push("    return this;");
        lines.push("  }");
        lines.push("");
      }

      lines.push(
        formatTsDoc(
          {
            summary: `Appends multiple ${property.name} items.`,
            params: [ { name: "items", description: `The \`${elementType}\` items to add.` } ],
            returns: BUILDER_RETURN_DESCRIPTION,
            indent: "  "
          }
        )
      );
      lines.push(`  ${addAllMethodName}(...items: ${elementType}[]): this`);
      lines.push("  {");
      lines.push(`    this._${property.name}.push(...items);`);
      lines.push("    return this;");
      lines.push("  }");
      lines.push("");

      if (property.name !== ELEMENTS_PROPERTY)
      {
        lines.push(
          formatTsDoc(
            {
              summary: `Appends a single ${singularName}.`,
              params: [ { name: "item", description: `The \`${elementType}\` item to add.` } ],
              returns: BUILDER_RETURN_DESCRIPTION,
              indent: "  "
            }
          )
        );
        lines.push(`  ${addMethodName}(item: ${elementType}): this`);
        lines.push("  {");
        lines.push(`    this._${property.name}.push(item);`);
        lines.push("    return this;");
        lines.push("  }");
        lines.push("");
      }
    }

    // We generate shortcut methods for every model in spec.uiElements
    for (const uiModel of spec.uiElements)
    {
      if (uiModel.isDslIgnored)
      {
        continue;
      }
      const { primary, aliases } = getFactoryNames(uiModel);
      const allNames = Array.from(new Set([ primary, ...aliases ]));
      const { requiredProperties, optionalProperties } = partitionProperties(uiModel.properties);

      const parameters: string[] = [];
      const callArguments: string[] = [];
      const methodDocParameters: TsDocParam[] = [];

      for (const property of requiredProperties)
      {
        parameters.push(`${property.name}: ${resolveTsType(property.type)}`);
        callArguments.push(property.name);
        methodDocParameters.push({ name: property.name, description: property.doc });
      }

      const {
        parameter: optionsParam,
        docParam: optionsDocParam
      } = formatOptionsParameter(optionalProperties, "Optional component settings");
      if (optionsParam)
      {
        parameters.push(optionsParam);
        callArguments.push("options");
        if (optionsDocParam)
        {
          methodDocParameters.push(optionsDocParam);
        }
      }

      for (const functionName of allNames)
      {
        const methodName = `add${capitalizeText(functionName)}`;
        lines.push(
          formatTsDoc(
            {
              summary: `Appends a \`${uiModel.name}\` component.`,
              remarks: uiModel.doc,
              params: methodDocParameters,
              returns: BUILDER_RETURN_DESCRIPTION,
              indent: "  "
            }
          )
        );
        lines.push(`  ${methodName}(${parameters.join(", ")}): this`);
        lines.push("  {");
        lines.push(`    return this.add(${functionName}(${callArguments.join(", ")}));`);
        lines.push("  }");
        lines.push("");
      }
    }

    const className = `${root.name}Class`;
    lines.push(
      formatTsDoc(
        {
          summary: `Finalizes and returns the complete strongly-typed \`${className}\` instance.`,
          returns: `The constructed \`${className}\` instance.`,
          indent: "  "
        }
      )
    );
    lines.push(`  build(): ${className}`);
    lines.push("  {");
    const buildArgs = formatClassInvocationArgs(rootRequiredProperties, rootArrayProperties, rootOptionalProperties, "builder");
    lines.push(`    return new ${className}(`);
    lines.push(`      ${buildArgs.join(",\n      ")}`);
    lines.push("    );");
    lines.push("  }");
    lines.push("");
    lines.push(
      formatTsDoc(
        {
          summary: `Serializes this builder into a strongly-typed, JSON-compatible plain object conforming to interface \`${root.name}\`.`,
          returns: `The plain object representation conforming to interface \`${root.name}\`.`,
          indent: "  "
        }
      )
    );
    lines.push(`  toJSON(): ${root.name}`);
    lines.push("  {");
    lines.push("    return this.build().toJSON();");
    lines.push("  }");
    lines.push("");
    lines.push(
      formatTsDoc(
        {
          summary: `Returns the compact JSON string representation of the built \`${className}\` instance with no indentation.`,
          returns: COMPACT_JSON_RETURN_DESCRIPTION,
          indent: "  "
        }
      )
    );
    lines.push("  toString(): string");
    lines.push("  {");
    lines.push("    return this.build().toString();");
    lines.push("  }");
    lines.push("}");
    lines.push("");

    // 7. We generate Static Root Model Helpers
    lines.push(
      formatTsDoc(
        {
          summary: `Static helper factory object for \`${root.name}\`.`
        }
      )
    );
    lines.push(`export const ${root.name} =`);
    lines.push("{");
    lines.push(
      formatTsDoc(
        {
          summary: `Creates a new fluent builder for constructing a \`${root.name}\`.`,
          params: constructorDocParameters,
          returns: `A new \`${builderClassName}\` instance.`,
          indent: "  "
        }
      )
    );
    lines.push(`  builder(${constructorArguments}): ${builderClassName}`);
    lines.push("  {");
    const builderCallArguments = rootRequiredProperties
      .map(
        (property) =>
        {
          return property.name;
        }
      )
      .join(", ");
    lines.push(`    return new ${builderClassName}(${builderCallArguments});`);
    lines.push("  },");
    lines.push("");

    const createParameters = rootNonTypeProperties
      .map(
        (property) =>
        {
          return `${property.name}${property.optional ? "?" : ""}: ${resolveTsType(property.type)}`;
        }
      )
      .join("; ");
    lines.push(
      formatTsDoc(
        {
          summary: `Creates a \`${className}\` directly from a properties object.`,
          params: [ { name: "params", description: "Configuration properties." } ],
          returns: `A completed \`${className}\` instance.`,
          indent: "  "
        }
      )
    );
    lines.push(`  create(params: { ${createParameters} }): ${className}`);
    lines.push("  {");
    const createArgs = formatClassInvocationArgs(rootRequiredProperties, rootArrayProperties, rootOptionalProperties, "params");
    lines.push(`    return new ${className}(`);
    lines.push(`      ${createArgs.join(",\n      ")}`);
    lines.push("    );");
    lines.push("  },");
    lines.push("");
    lines.push(
      formatTsDoc(
        {
          summary: `Parses a JSON string or raw object into a validated \`${className}\` instance.`,
          params: [
            { name: "json", description: "JSON string or parsed JavaScript object to validate and hydrate." },
            { name: "withDeepValidation", description: "Whether to recursively validate all nested child entities." }
          ],
          returns: `A strongly-typed \`${className}\` instance.`,
          remarks: `Throws an \`Error\` if the input does not conform to the \`${root.name}\` schema.`,
          indent: "  "
        }
      )
    );
    lines.push(`  parse(json: string | unknown, withDeepValidation = true): ${className}`);
    lines.push("  {");
    lines.push("    const data: unknown = typeof json === \"string\" ? JSON.parse(json) : json;");
    lines.push(`    if (!is${root.name}(data, withDeepValidation))`);
    lines.push("    {");
    lines.push(`      throw new Error("Invalid JSON: value does not match the \`${root.name}\` schema.");`);
    lines.push("    }");
    lines.push(`    return ${root.name}.create(data);`);
    lines.push("  }");
    lines.push("};");
    lines.push("");

    // 8. We generate create<RootModel> and parse<RootModel> Functional Factories
    const createFunctionName = `create${root.name}`;
    const rootOptionalCreateFields = rootNonTypeProperties
      .filter(
        (property) =>
        {
          return !rootRequiredProperties.includes(property);
        }
      )
      .map(
        (property) =>
        {
          return `${property.name}?: ${resolveTsType(property.type)}`;
        }
      )
      .join("; ");
    lines.push(
      formatTsDoc(
        {
          summary: `Functional helper to create a \`${className}\` instance directly.`,
          remarks: root.doc,
          params: [
            ...constructorDocParameters,
            ...(rootOptionalCreateFields.length > 0 ? [ {
              name: "options",
              description: "Optional configuration (description, elements, actions)."
            } ] : [])
          ],
          returns: `A strongly-typed \`${className}\` instance.`
        }
      )
    );
    const optionsParameter = rootOptionalCreateFields.length > 0
      ? (rootRequiredProperties.length > 0 ? `, options?: { ${rootOptionalCreateFields} }` : `options?: { ${rootOptionalCreateFields} }`)
      : "";
    lines.push(`export function ${createFunctionName}(${constructorArguments}${optionsParameter}): ${className}`);
    lines.push("{");
    const helperArgs = formatClassInvocationArgs(rootRequiredProperties, rootArrayProperties, rootOptionalProperties, "helper");
    lines.push(`  return new ${className}(`);
    lines.push(`    ${helperArgs.join(",\n    ")}`);
    lines.push("  );");
    lines.push("}");
    lines.push("");

    const parseFunctionName = `parse${root.name}`;
    lines.push(
      formatTsDoc(
        {
          summary: `Parses a JSON string or raw object into a validated \`${className}\` instance.`,
          remarks: root.doc,
          params: [
            { name: "json", description: "JSON string or parsed JavaScript object to validate and hydrate." },
            { name: "withDeepValidation", description: "Whether to recursively validate all nested child entities." }
          ],
          returns: `A strongly-typed \`${className}\` instance.`
        }
      )
    );
    lines.push(`export function ${parseFunctionName}(json: string | unknown, withDeepValidation = true): ${className}`);
    lines.push("{");
    lines.push(`  return ${root.name}.parse(json, withDeepValidation);`);
    lines.push("}");
    lines.push("");
  }

  // 9. We generate Functional DSL Factories for all models from AST
  lines.push(FUNCTIONAL_FACTORIES_SECTION_HEADER);
  lines.push("");

  for (const model of spec.models)
  {
    if (polymorphicRootNames.has(model.name) || model.isDslRoot || spec.rootModels.includes(model) || model.isDslIgnored)
    {
      continue;
    }
    const factoryLines = generateModelFactory(model);
    lines.push(...factoryLines);
  }

  // 10. We generate Type Guards dynamically from AST polymorphic roots, supporting models, and root models
  lines.push(TYPE_GUARDS_SECTION_HEADER);
  lines.push("");

  const supportingModels = spec.models.filter(
    (model) =>
    {
      return (
        !polymorphicRootNames.has(model.name) &&
        (!model.baseModelName || !polymorphicRootNames.has(model.baseModelName)) &&
        !model.isDslRoot &&
        !spec.rootModels.includes(model) &&
        !model.isDslIgnored
      );
    }
  );

  for (const model of supportingModels)
  {
    lines.push(
      formatTsDoc(
        {
          summary: `Type guard predicate verifying whether an unknown value conforms to \`${model.name}\`.`,
          params: [
            { name: "value", description: "The value to inspect." },
            { name: "withDeepValidation", description: "Whether to recursively validate all properties." }
          ],
          returns: `\`true\` if the value conforms to \`${model.name}\`, otherwise \`false\`.`
        }
      )
    );
    lines.push(`export function is${model.name}(value: unknown, withDeepValidation = false): value is ${model.name}`);
    lines.push("{");
    lines.push("  if (typeof value !== \"object\" || value === null)");
    lines.push("  {");
    lines.push("    return false;");
    lines.push("  }");
    lines.push("  if (!withDeepValidation)");
    lines.push("  {");
    lines.push("    return true;");
    lines.push("  }");
    lines.push(`  const element = value as ${model.name};`);
    const propertyChecks = generateModelPropertyChecks(model.properties, spec, "element");
    if (propertyChecks.length === 0)
    {
      lines.push("  return true;");
    }
    else
    {
      lines.push(`  return ${propertyChecks.join(" &&\n    ")};`);
    }
    lines.push("}");
    lines.push("");
  }

  for (const root of spec.polymorphicRoots)
  {
    lines.push(
      formatTsDoc(
        {
          summary: `Type guard predicate verifying whether an unknown value conforms to \`${root.name}\`.`,
          params: [
            { name: "value", description: "The value to inspect." },
            { name: "withDeepValidation", description: "Whether to recursively validate all properties." }
          ],
          returns: `\`true\` if the value is a valid \`${root.name}\`, otherwise \`false\`.`
        }
      )
    );
    lines.push(`export function is${root.name}(value: unknown, withDeepValidation = false): value is ${root.name}`);
    lines.push("{");
    lines.push(`  if (typeof value !== "object" || value === null || !("${root.discriminatorProperty}" in value) || typeof (value as { ${root.discriminatorProperty}: unknown }).${root.discriminatorProperty} !== "string")`);
    lines.push("  {");
    lines.push("    return false;");
    lines.push("  }");
    lines.push("  if (!withDeepValidation)");
    lines.push("  {");
    lines.push("    return true;");
    lines.push("  }");
    lines.push(`  const element = value as ${root.name};`);
    lines.push(`  switch (element.${root.discriminatorProperty})`);
    lines.push("  {");
    for (const derivedModel of root.derivedModels)
    {
      if (derivedModel.discriminatorValue && !derivedModel.isDslIgnored)
      {
        lines.push(`    case "${derivedModel.discriminatorValue}":`);
        lines.push(`      return is${derivedModel.name}(element, true);`);
      }
    }
    lines.push("    default:");
    lines.push("      return false;");
    lines.push("  }");
    lines.push("}");
    lines.push("");

    for (const derivedModel of root.derivedModels)
    {
      if (derivedModel.discriminatorValue && !derivedModel.isDslIgnored)
      {
        const guardName = `is${derivedModel.name}`;
        lines.push(
          formatTsDoc(
            {
              summary: `Type guard predicate narrowing a value to \`${derivedModel.name}\`.`,
              params: [
                { name: "value", description: "The value to inspect." },
                { name: "withDeepValidation", description: "Whether to recursively validate all properties." }
              ],
              returns: `\`true\` if the value is a \`${derivedModel.name}\` (type = "${derivedModel.discriminatorValue}"), otherwise \`false\`.`
            }
          )
        );
        lines.push(`export function ${guardName}(value: unknown, withDeepValidation = false): value is ${derivedModel.name}`);
        lines.push("{");
        lines.push(`  if (typeof value !== "object" || value === null || !("${root.discriminatorProperty}" in value) || (value as { ${root.discriminatorProperty}: unknown }).${root.discriminatorProperty} !== "${derivedModel.discriminatorValue}")`);
        lines.push("  {");
        lines.push("    return false;");
        lines.push("  }");
        lines.push("  if (!withDeepValidation)");
        lines.push("  {");
        lines.push("    return true;");
        lines.push("  }");
        lines.push(`  const element = value as ${derivedModel.name};`);
        const propertyChecks = generateModelPropertyChecks(derivedModel.properties, spec, "element");
        if (propertyChecks.length === 0)
        {
          lines.push("  return true;");
        }
        else
        {
          lines.push(`  return ${propertyChecks.join(" &&\n    ")};`);
        }
        lines.push("}");
        lines.push("");
      }
    }
  }

  for (const root of rootModels)
  {
    lines.push(
      formatTsDoc(
        {
          summary: `Type guard predicate verifying whether an unknown value conforms to \`${root.name}\`.`,
          params: [
            { name: "value", description: "The value to inspect." },
            { name: "withDeepValidation", description: "Whether to recursively validate all properties." }
          ],
          returns: `\`true\` if the value is a valid \`${root.name}\`, otherwise \`false\`.`
        }
      )
    );
    lines.push(`export function is${root.name}(value: unknown, withDeepValidation = false): value is ${root.name}`);
    lines.push("{");
    lines.push("  if (typeof value !== \"object\" || value === null)");
    lines.push("  {");
    lines.push("    return false;");
    lines.push("  }");
    const shallowConditions: string[] = [];
    if (root.properties.some((property) => property.name === SCHEMA_VERSION_PROPERTY))
    {
      shallowConditions.push(`!("${SCHEMA_VERSION_PROPERTY}" in value) || (value as { ${SCHEMA_VERSION_PROPERTY}: unknown }).${SCHEMA_VERSION_PROPERTY} !== "${SCHEMA_VERSION_VALUE}"`);
    }
    for (const property of root.properties.filter((property) => !property.optional && property.defaultValue === undefined && property.name !== DISCRIMINATOR_PROPERTY && property.name !== SCHEMA_VERSION_PROPERTY))
    {
      shallowConditions.push(`!("${property.name}" in value)`);
    }
    if (shallowConditions.length > 0)
    {
      lines.push(`  if (${shallowConditions.join(" || ")})`);
      lines.push("  {");
      lines.push("    return false;");
      lines.push("  }");
    }
    lines.push("  if (!withDeepValidation)");
    lines.push("  {");
    lines.push("    return true;");
    lines.push("  }");
    lines.push(`  const element = value as ${root.name};`);
    const propertyChecks = generateModelPropertyChecks(root.properties, spec, "element");
    if (propertyChecks.length === 0)
    {
      lines.push("  return true;");
    }
    else
    {
      lines.push(`  return ${propertyChecks.join(" &&\n    ")};`);
    }
    lines.push("}");
    lines.push("");
  }

  return lines.join("\n");
}

function generateDeepTypeCheck(access: string, type: GrammarType, spec: GrammarSpec): string
{
  switch (type.kind)
  {
    case "string":
      return `typeof ${access} === "string"`;
    case "number":
      return `typeof ${access} === "number"`;
    case "boolean":
      return `typeof ${access} === "boolean"`;
    case "literal":
      return `${access} === ${type.name}`;
    case "enum":
      return `Object.values(${type.name}).includes(${access} as ${type.name})`;
    case "model":
    {
      const model = spec.models.find((model) => model.name === type.name);
      if (model && !model.isDslIgnored)
      {
        return `is${model.name}(${access}, true)`;
      }
      return `(typeof ${access} === "object" && ${access} !== null)`;
    }
    case "array":
    {
      if (type.elementType)
      {
        const itemCheck = generateDeepTypeCheck("item", type.elementType, spec);
        return `(Array.isArray(${access}) && ${access}.every((item) => ${itemCheck}))`;
      }
      return `Array.isArray(${access})`;
    }
    case "record":
      return `(typeof ${access} === "object" && ${access} !== null)`;
    case "union":
    {
      if (type.unionTypes && type.unionTypes.length > 0)
      {
        const unionChecks = type.unionTypes.map((unionType) => generateDeepTypeCheck(access, unionType, spec));
        return `(${unionChecks.join(" || ")})`;
      }
      return "true";
    }
    default:
      return "true";
  }
}
