import {
  createUiContainer,
  string,
  table,
  tableColumn,
  TableColumnAlign,
  TableColumnWidthMode,
  tableRow,
  type TableRow,
  TextIntensity,
  TextWeight,
  type UiContainer,
  type UiElement
} from "@picteus/internal-extension-sdk";


export class Automatic1111Instruction
{

  constructor(readonly key: string, readonly value: string | Record<string, any> | Array<Record<string, any>>)
  {
    this.key = key;
    this.value = value;
  }

}

/**
 * The instructions of an image generated by Automatic1111.
 */
export class Automatic1111UserComment
{

  static parse(userCommentOrParameters: string): Automatic1111UserComment
  {
    const elements = Automatic1111UserComment.extractUserComment(userCommentOrParameters);
    if (elements === undefined)
    {
      throw new Error("The image does not contain valid Automatic1111 metadata");
    }
    const { positive, negative, rest } = elements;
    const instructions: Automatic1111Instruction[] = [];
    const addInstruction = (key: string, value: string): void =>
    {
      if (value !== "Undefined")
      {
        instructions.push(new Automatic1111Instruction(key, Automatic1111UserComment.parseValue(value)));
      }
    };
    if (rest !== "")
    {
      let string = rest;
      while (true)
      {
        const result1 = /^([^"^:]*): .*$/m.exec(string);
        if (result1 !== null)
        {
          const key = result1[1];
          string = string.substring(key.length + 2);
          const result2 = /^([^"^:]*): .*$/m.exec(string);
          if (result2 !== null)
          {
            const value = result2[1].substring(0, result2[1].lastIndexOf(","));
            addInstruction(key, value);
            string = string.substring(value.length + 2);
          }
          else
          {
            const result3 = /^(.*?), ([^"^:]*): .*$/m.exec(string);
            if (result3 !== null)
            {
              const value = result3[1];
              addInstruction(key, value);
              string = string.substring(value.length + 2);
            }
            else
            {
              addInstruction(key, string);
              break;
            }
          }
        }
        else
        {
          throw new Error("Unexpected Automatic1111 metadata format");
        }
      }
    }
    return new Automatic1111UserComment(positive, negative, instructions);
  }

  static extractUserComment(userCommentOrParameters: string): {
    positive: string,
    negative: string | undefined,
    unexpected: string | undefined,
    rest: string
  } | undefined
  {
    let positive: string;
    let negative: string | undefined;
    let unexpected: string | undefined;
    let rest: string;
    {
      const newLine = "\n";
      const negativePromptCoreMarker = "Negative prompt:";
      const negativePromptMarker = `${newLine}${negativePromptCoreMarker}`;
      const negativePromptIndex = userCommentOrParameters.indexOf(negativePromptMarker);
      if (negativePromptIndex !== -1)
      {
        positive = userCommentOrParameters.substring(0, negativePromptIndex).trim();
        const remainingString = userCommentOrParameters.substring(negativePromptIndex + negativePromptMarker.length);
        const result = /^(.*)\n[^:\n]*: .*$/sm.exec(remainingString);
        negative = (result === null ? remainingString : result[1]).trim();
        rest = result === null ? "" : remainingString.substring(result[1].length + 1);
      }
      else
      {
        const tokens = userCommentOrParameters.split(newLine);
        if (tokens.length === 1)
        {
          // This does not correspond to a valid Automatic1111 generated image. This happens in the case of an image generated by ReActor, https://github.com/Gourieff/sd-webui-reactor
          return undefined;
        }
        else
        {
          let index = 0;
          positive = tokens[index++];
          if (tokens.length >= 3)
          {
            negative = tokens[index++];
            unexpected = tokens.slice(index++, tokens.length - 1).join(newLine);
          }
          rest = tokens[tokens.length - 1];
        }
      }
    }
    return { positive, negative, unexpected, rest };
  }

  static parseValue(value: string): string | Record<string, any> | Array<Record<string, any>>
  {
    const trimmedValue = value.trim();
    if ((trimmedValue.startsWith("{") && trimmedValue.endsWith("}")) || (trimmedValue.startsWith("[") && trimmedValue.endsWith("]")))
    {
      try
      {
        const parsed = JSON.parse(trimmedValue);
        if (typeof parsed === "object" && parsed !== null)
        {
          return parsed;
        }
      }
      catch (error)
      {
        // Value is not valid JSON
      }
    }
    return value;
  }

  constructor(readonly positive: string, readonly negative: string | undefined, readonly instructions: Automatic1111Instruction[])
  {
  }

  toUiContainer(): UiContainer
  {
    const elements: UiElement[] = [];
    const rows: TableRow[] = [];
    const firstColumnOptions = { modifiers: { weight: TextWeight.heavy, intensity: TextIntensity.low } };
    const copyableOptions = { modifiers: { copyable: true } };
    for (const instruction of this.instructions)
    {
      let element: UiElement;
      if (typeof instruction.value === "string")
      {
        if (instruction.value.length > 0)
        {
          element = string(instruction.value, copyableOptions);
        }
      }
      else
      {
        if (Array.isArray(instruction.value) === true)
        {
          const values: Array<Record<string, any>> = instruction.value;
          if (values.length > 0)
          {
            const tables = values.map(value => table(Object.entries(value).map(([ key, value ]) => tableRow([ string(key), string(value.toString()) ]))));
            element = table(tables.map(table => tableRow([ table ])));
          }
        }
        else
        {
          const value: Record<string, any> = instruction.value;
          if (Object.keys(value).length > 0)
          {
            element = table(Object.entries(value).map(([ key, value ]) => tableRow([ string(key), string(value.toString()) ])));
          }
        }
      }
      if (element !== undefined)
      {
        rows.push(tableRow([ string(instruction.key, firstColumnOptions), element ]));
      }
    }
    elements.push(table(rows, {
      withRowSeparators: true,
      columns:
        [
          tableColumn({
            align: TableColumnAlign.left,
            width: 25,
            widthMode: TableColumnWidthMode.maximum
          }),
          tableColumn({ align: TableColumnAlign.left })
        ]
    }));
    return createUiContainer({ elements });
  }

}
