export const PICTEUS_NAMESPACE = "Picteus";

const GENERATED_FILE_HEADER_TEXT = "Auto-generated by @picteus/specification-factory. Do not edit directly.";
const GENERATED_FILE_HEADER_SEPARATOR = "---------------------------------------------------------------------------";

export function createGeneratedFileHeader(commentPrefix: "//" | "#"): string[]
{
  return [
    `${commentPrefix} ${GENERATED_FILE_HEADER_SEPARATOR}`,
    `${commentPrefix} ${GENERATED_FILE_HEADER_TEXT}`,
    `${commentPrefix} ${GENERATED_FILE_HEADER_SEPARATOR}`
  ];
}
