export const PICTEUS_NAMESPACE = "Picteus";

export interface DocumentationType
{
  readonly summary?: string;
  readonly doc?: string;
}

export function getDocumentationText(documentation: DocumentationType): string | undefined
{
  const text = [ documentation.summary, documentation.doc ]
    .filter((value): value is string => Boolean(value))
    .join("\n\n");
  return text || undefined;
}

const GENERATED_FILE_HEADER_TEXT = "Auto-generated by @picteus/specification-factory. Do not edit directly.";
const GENERATED_FILE_HEADER_SEPARATOR = "---------------------------------------------------------------------------";

export function createGeneratedFileHeader(commentPrefix: "//" | "#"): string[]
{
  return [
    `${commentPrefix} ${GENERATED_FILE_HEADER_SEPARATOR}`,
    `${commentPrefix} ${GENERATED_FILE_HEADER_TEXT}`,
    `${commentPrefix} ${GENERATED_FILE_HEADER_SEPARATOR}`
  ];
}
