name: Back-end CI
run-name: Manages the back-end dependencies installation, compilation and tests

on:
  push:
    branches: [ 'master' ]
    paths-ignore:
      - '.github/workflows/**'
  pull_request:
    branches: [ 'master' ]
  workflow_dispatch:
    inputs:
      os:
        description: 'OS to run against?'
        type: choice
        required: true
        options:
          - '["windows-latest"]'
          - '["windows-11-arm"]'
          - '["macos-26"]'
          - '["macos-15-intel"]'
          - '["ubuntu-latest"]'
        default: '["macos-26"]'

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: ${{ (github.event_name == 'push' && fromJson('["macos-26"]')) || fromJson(inputs.os) }}
    runs-on: ${{ matrix.os }}
    steps:
      - id: checkout
        name: Checks out the project
        uses: actions/checkout@v7
        with:
          submodules: 'recursive'
          fetch-depth: 0
          persist-credentials: true
      - id: node-setup
        name: Sets up Node
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
          cache: 'npm'
      - id: java-setup
        name: Sets up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
      - id: install
        if: ${{ env.skip != 'true' }}
        name: Installs the prerequisites and back-end dependencies
        run: npm install && npm run this:prerequisites && npm run shared-back-end:prerequisites && npm run back-end:prerequisites && npm run extensions:prerequisites && npm run extensions:sdk:build
      - id: compile
        name: Generates some code and compiles
        run: npm --prefix back-end run prisma:generate && npm --prefix back-end run compile
      - id: tests
        name: Runs the tests
        run: npm --prefix back-end run ci:test
